version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build phase"
      - aws cloudformation package --template-file template.yaml --s3-bucket update-lambda-code --output-template-file packaged-template.yaml
      - zip -r my-code.zip lambda_function.py   
      - aws s3 cp my-code.zip s3://update-lambda-code/lambda/my-code.zip
  post_build:
    commands:
      - echo "Post Build Phase"
      # Retrieve the S3 object version ID
      - |
        OBJECT_VERSION=$(aws s3api head-object --bucket update-lambda-code --key lambda/my-code.zip --query "VersionId" --output text)
        echo "S3 Object Version ID: $OBJECT_VERSION"
      # Update the CloudFormation template with the S3 object version ID
      - sed -i "s/S3ObjectVersionPlaceholder/$OBJECT_VERSION/" packaged-template.yaml
      # Display the modified CloudFormation template
      - cat packaged-template.yaml


artifacts:
  type: zip
  files:
    - packaged-template.yaml
