version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build phase"
  post_build:
    commands:
      - echo "Post build phase"
      - aws cloudformation package --template-file template.yaml --s3-bucket cicd-shared-assets --output-template-file $CODEBUILD_SRC_DIR/packaged-template.yaml

artifacts:
  type: zip
  files:
    - packaged-template.yaml
