version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build phase"
      - aws cloudformation package --template-file template.yaml --s3-bucket update-lambda-code --output-template-file packaged-template.yaml
      - zip -r my-code.zip lambda_function.py   
      - aws s3 cp my-code.zip s3://update-lambda-code/lambda/my-code.zip
      - export S3_VERSION=$(aws s3api list-object-versions --bucket update-lambda-code --prefix lambda/my-code.zip --query 'Versions[0].VersionId' --output text)
      - echo "S3 Version ID: $S3_VERSION"
      - sed -i "s/S3ObjectVersion: '.*'/S3ObjectVersion: '$S3_VERSION'/" packaged-template.yaml
  post_build:
    commands:
      - echo "Post Build Phase"
      
artifacts:
  type: zip
  files:
    - packaged-template.yaml
