version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build phase"
      - aws cloudformation package --template-file template.yaml --s3-bucket update-lambda-code --output-template-file packaged-template.yaml
      - zip -r my-lambda-code.zip lambda_function.py   # Package your Lambda function code
      - aws s3 cp my-lambda-code.zip s3://update-lambda-code/lambda/my-lambda-code.zip
artifacts:
  type: zip
  files:
    - packaged-template.yaml
