version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build phase"
      # Additional build commands or tests can be added here
  post_build:
    commands:
      - echo "Post build phase"
      - aws cloudformation package --template-file template.yml --s3-bucket cicd-shared-assets --output-template-file packaged-template.yml

artifacts:
  type: zip
  files:
    - packaged-template.yml
