AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::update-lambda-code/*"

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
          - MyLambdaRole
          - Arn
      FunctionName: MyLambdaFunction
      Runtime: python3.11
      Timeout: 60
      MemorySize: 128
      Code:
        S3Bucket: update-lambda-code
        S3Key: lambda/my-code.zip
        S3ObjectVersion:
          Fn::GetAtt:
            - GetLatestS3ObjectVersion
            - VersionId

  GetLatestS3ObjectVersion:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - GetLatestS3ObjectVersionRole
          - Arn
      FunctionName: GetLatestS3ObjectVersion
      Runtime: python3.8
      Timeout: 30
      MemorySize: 128
      Code:
        S3Bucket: !Ref AWS::AccountId
        S3Key: custom-resources/get-latest-s3-version.zip

  GetLatestS3ObjectVersionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetLatestS3ObjectVersionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObjectVersion
                  - s3:ListObjectVersions
                Resource: !Sub "arn:aws:s3:::update-lambda-code/*"

Outputs:
  MyLambdaFunctionArn:
    Value: !GetAtt MyLambdaFunction.Arn
    Description: "ARN of the Lambda Function"
